### ISSUE TITLE
Knex errors in prod

### ISSUE THREAD

**Issue by craig-mulligan** [resin-io/resin-blog#37]
Need to investigate where these come from: 
```
resin blog production-4 (err): ERROR: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call? 
resin blog production-4 (err):  Rendering Error Page 
resin blog production-4 (err):  Ghost caught a processing error in the middleware layer. 
resin blog production-4 (err):  Error: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
resin blog production-4 (err):     at /var/www/resin-blog/node_modules/knex/lib/runner.js:138:30
resin blog production-4 (err):     at tryCatcher (/var/www/resin-blog/node_modules/knex/node_modules/bluebird/js/main/util.js:26:23)
resin blog production-4 (err):     at CatchFilter.doFilter (/var/www/resin-blog/node_modules/knex/node_modules/bluebird/js/main/catch_filter.js:40:36)
resin blog production-4 (err):     at CatchFilter.tryCatcher (/var/www/resin-blog/node_modules/knex/node_modules/bluebird/js/main/util.js:26:23)
resin blog production-4 (err):     at Promise._settlePromiseFromHandler (/var/www/resin-blog/node_modules/knex/node_modules/bluebird/js/main/promise.js:507:31)
resin blog production-4 (err):     at Promise._settlePromiseAt (/var/www/resin-blog/node_modules/knex/node_modules/bluebird/js/main/promise.js:581:18)
resin blog production-4 (err):     at Promise._settlePromises (/var/www/resin-blog/node_modules/knex/node_modules/bluebird/js/main/promise.js:697:14)
resin blog production-4 (err):     at Async._drainQueue (/var/www/resin-blog/node_modules/knex/node_modules/bluebird/js/main/async.js:123:16)
resin blog production-4 (err):     at Async._drainQueues (/var/www/resin-blog/node_modules/knex/node_modules/bluebird/js/main/async.js:133:10)
resin blog production-4 (err):     at Async.drainQueues (/var/www/resin-blog/node_modules/knex/node_modules/bluebird/js/main/async.js:15:14)
resin blog production-4 (err):     at process._tickDomainCallback (node.js:492:13) 
resin blog production-4 (err): WARNING: Ghost is attempting to use a direct method to send email. 
resin blog production-4 (err): It is recommended that you explicitly configure an email service.
```

**Comment by craig-mulligan** [comment]
Hit the same issue today, seems to be happening increasingly often. 

Output from todays err: 
```
resin blog production-2 (err):  Error: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?

resin blog production-2 (err):     at /var/www/resin-blog/node_modules/knex/lib/runner.js:138:30

resin blog production-2 (err):     at tryCatcher (/var/www/resin-blog/node_modules/knex/node_modules/bluebird/js/main/util.js:26:23)

resin blog production-2 (err):     at CatchFilter.doFilter (/var/www/resin-blog/node_modules/knex/node_modules/bluebird/js/main/catch_filter.js:40:36)

resin blog production-2 (err):     at CatchFilter.tryCatcher (/var/www/resin-blog/node_modules/knex/node_modules/bluebird/js/main/util.js:26:23)

resin blog production-2 (err):     at Promise._settlePromiseFromHandler (/var/www/resin-blog/node_modules/knex/node_modules/bluebird/js/main/promise.js:507:31)

resin blog production-2 (err):     at Promise._settlePromiseAt (/var/www/resin-blog/node_modules/knex/node_modules/bluebird/js/main/promise.js:581:18)

resin blog production-2 (err):     at Promise._settlePromises (/var/www/resin-blog/node_modules/knex/node_modules/bluebird/js/main/promise.js:697:14)

resin blog production-2 (err):     at Async._drainQueue (/var/www/resin-blog/node_modules/knex/node_modules/bluebird/js/main/async.js:123:16)

resin blog production-2 (err):     at Async._drainQueues (/var/www/resin-blog/node_modules/knex/node_modules/bluebird/js/main/async.js:133:10)

resin blog production-2 (err):     at Async.drainQueues (/var/www/resin-blog/node_modules/knex/node_modules/bluebird/js/main/async.js:15:14)

resin blog production-2 (err):     at process._tickDomainCallback (node.js:502:13) 
```

**Comment by craig-mulligan** [comment]
For reference the issue is solved by restarting the node process with pm2. 
```
sudo pm2 restart <pm2-process-id>
```
